### ISSUE TITLE
Someway to use Webfonts?

### ISSUE THREAD

**Issue by alvarosg88** [gamestdio/three-text2d#6]
Hi. I was wondering if there is anyway to include an imported webfont (for example anyone from Google Fonts, like Montserrat). Thanks.

**Comment by endel** [comment]
Hey @alvarosg88, 

Absolutely. One trick I tend to do is creating an invisible element in the DOM to preload the font, and then just use it in the `Text2D` constructor. 

Take a look at the example below:

**CSS**

```css
@font-face {
  font-family: 'BitBold';
  src: url("../fonts/BitBold.eot");
  src: url("../fonts/BitBold.eot?#iefix") format('embedded-opentype'), url("../fonts/BitBold.woff") format('woff'), url("../fonts/BitBold.ttf") format('truetype'), url("../fonts/BitBold.svg#BitBold") format('svg');
  font-weight: normal;
  font-style: normal;
}

p.font-bitbold {
  position: absolute;
  font-family: 'BitBold';
  visibility: hidden;
}
```

**HTML**
```html
<p class="font-bitbold">.<p>
```

**JavaScript**

```javascript
var text = new Text2D("Using webfont", { 
  font: '30px BitBold', 
  fillStyle: '#000000' , 
  antialias: false
})

container.add( text )
```

Hope it helps. Cheers!
